FROM node:18-alpine as base

RUN apk add --no-cache libc6-compat tini
WORKDIR /app
COPY package.json yarn.lock* ./

FROM base AS deps
RUN yarn install --prod --frozen-lockfile

FROM deps AS build
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

FROM base as prod
ENV NODE_ENV production
COPY --from=deps /app/node_modules /app/node_modules
COPY --from=build /app/dist /app/dist
EXPOSE 8000
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["sh", "-c", "yarn start:prod"]
