version: '3.8'
services:
  database:
    image: postgres:13
    container_name: postgres-db
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: yushaku
      POSTGRES_PASSWORD: 123
      POSRGRES_DB: nest
    networks:
      - default

  # redis:
  #   image: 'redis:7.0-alpine'
  #   volumes:
  #     - ./.docker/redis:/data
  #   ports:
  #     - '6379:6379'
  #   networks:
  #     - default

  # redis-commander:
  #   container_name: redis-commander
  #   image: rediscommander/redis-commander:latest
  #   restart: always
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #   ports:
  #     - '8081:8081'

  minio-server:
    container_name: minio-server
    image: minio/minio
    ports:
      - "9000:9000"
      - '9001:9001'
    volumes:
      - ./.docker/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

networks:
  default:
